source 'https://rubygems.org'
gem 'rails', '4.2.0.beta2'
gem 'pg'
gem 'sass-rails', '~> 5.0.0.beta1'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails', '~> 4.0.0.beta2'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'unicorn'
gem 'devise'
gem 'omniauth'
gem 'omniauth-twitter'
gem 'omniauth-facebook'
gem 'omniauth-linkedin'
gem 'omniauth-google-oauth2'
gem 'omniauth-instagram'
gem 'omniauth-github'
gem 'omniauth-tumblr'
gem 'paperclip'
gem 'domp'

group :development, :test do
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'web-console', '~> 2.0.0.beta4'
  gem 'spring'
  gem 'dotenv-rails'
end
