AuthenticationProvider.create(name: 'facebook')
AuthenticationProvider.create(name: 'twitter')
AuthenticationProvider.create(name: 'linkedin')
AuthenticationProvider.create(name: 'google_oauth2')
AuthenticationProvider.create(name: 'instagram')